definitions:
  model.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  model.UserResponseDTO:
    properties:
      email:
        type: string
      id:
        type: integer
      joined_at:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/email:
    get:
      consumes:
      - application/json
      description: Get user detail based on email query param
      parameters:
      - description: User Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get user by email
      tags:
      - users
swagger: "2.0"
